HairSalon/Models/Client.cs
namespace HairSalon.Models
{
  public class Client
  {
    public int ClientId { get; set; }
    public string Name { get; set; }
    // public datetime AppointmentDate { get; set; }
    public string PhoneNumber { get; set; }
    public int Age { get; set; }
    public int StylistId { get; set; }
    public virtual Stylist Stylist { get; set; }
  }
}

HairSalon/Models/HairSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
  public class HairSalonContext : DbContext
  {
    public virtual DbSet<Stylist> Stylists { get; set; }
    public DbSet<Client> Clients { get; set; }

    public HairSalonContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

HairSalon/Models/Stylest.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
  public class Stylist
  {
    public Stylist()
    {
      this.Clients = new HashSet<Client>();
    }

    public int StylistId { get; set; }
    public string Name { get; set; }
    public string Speciallity { get; set; }
    public float PayRate { get; set; }
    public virtual ICollection<Client> Clients { get; set; }
  }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;

namespace HairSalon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly HairSalonContext _db;

    public ClientsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Client> model = _db.Clients.Include(client => client.Stylist).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Client client)
    {
      _db.Clients.Add(client);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }
    public ActionResult Edit(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View(thisClient);
    }
    [HttpPost]
    public ActionResult Edit(Client client)
    {
      _db.Entry(client).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      _db.Clients.Remove(thisClient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HairSalon.Controllers
{
  public class HomeController : Controller
  {

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }

  }
}

HairSalon/Controllers/StylistsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;

namespace HairSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly HairSalonContext _db;
    public StylistsController(HairSalonContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
      _db.Stylists.Add(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }
    public ActionResult Edit(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost]
    public ActionResult Edit(Stylist stylist)
    {
      _db.Entry(stylist).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      _db.Stylists.Remove(thisStylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

HairSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h4>Add a new client</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)<br>

  @Html.LabelFor(model => model.PhoneNumber)
  @Html.TextBoxFor(model => model.PhoneNumber)<br>

  @Html.LabelFor(model => model.Age)
  @Html.TextBoxFor(model => model.Age,
new {@class = "form-control", type="number", required="number"})<br>




  @Html.LabelFor(model => model.Stylist)
  @Html.DropDownList("StylistId")

  <input type="submit" value="Add new client" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all clients", "Index")</p>

HairSalon/Views/Clients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

HairSalon/Views/Clients/DeleteAll.cshtml
@{
  Layout = "_Layout";
}

<h1>Your list has been cleared!</h1>
<p><a href="/clients">Back to list of clients.</a></p>

HairSalon/Views/Clients/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Client Details</h2>
<hr />
<h3> @Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3> @Html.DisplayNameFor(model => model.Age): @Html.DisplayFor(model => model.Age)</h3>
<h3>Client's Phone Number: @Html.DisplayFor(model => model.PhoneNumber)</h3>
<p>@Html.ActionLink("Edit Client", "Edit", new { id = Model.ClientId })</p>
<p>@Html.ActionLink("Delete Client", "Delete", new { id = Model.ClientId })</p>
<p>@Html.ActionLink("Back to list of clients", "Index")</p>

HairSalon/Views/Clients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Edit</h2>

<h4>Edit this Client: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.ClientId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)


  @Html.LabelFor(model => model.PhoneNumber)
  @Html.TextBoxFor(model => model.PhoneNumber)<br>

  @Html.LabelFor(model => model.Age)
  @Html.TextBoxFor(model => model.Age,
new {@class = "form-control", type="number", required="number"})<br>

  @Html.LabelFor(model => model.Stylist)
  @Html.DropDownList("StylistId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

HairSalon/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Client>;

<h1>Clients</h1>

@if (@Model.Count == 0)
{
  <h3>No clients have been added yet!</h3>
}

@foreach (Client client in Model)
{
  <li>@Html.ActionLink($"{client.Name}", "Details", new { id = client.ClientId }) |Stylist reserved: @client.Stylist.Name
</li>
}

<p>@Html.ActionLink("Add new client", "Create")</p>

HairSalon/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1> Hey Get your hair did!</h1>
<p>@Html.ActionLink("See all clients", "Index", "Clients")</p>
<p> @Html.ActionLink("Checkout all our stylists", "Index", "Stylists") </p>

HairSalon/Views/Shared/Footer.cshtml
<div id="footer">@Html.ActionLink("Homepage", "Index", "Home")</div>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Eau Claire's salon!</title>
  <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
  <link rel="stylesheet" href="~/css/styles.css">
</head>

<body>
  @RenderBody()
  @Html.Partial("Footer")
</body>

</html>

HairSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h4>Add a new stylist</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name, new {@class = "form-control", type="text", required="text"})

  @Html.LabelFor(model => model.Speciallity)
  @Html.TextBoxFor(model => model.Name, new {@class = "form-control", type="text", required="text"})

  @Html.LabelFor(model => model.PayRate)
  @Html.TextBoxFor(model => model.PayRate, new {@class = "form-control", type="number", step=".01", required="number"})

  <input type="submit" value="Add new stylist" />
}
<p>@Html.ActionLink("Show all stylists", "Index")</p>

HairSalon/Views/Stylists/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h2>Are you sure you want to delete this stylist?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List of stylists", "Index")

HairSalon/Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h2>Stylist's Details:</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.Speciallity): @Html.DisplayFor(model => model.Speciallity)</h3>
<h3>@Html.DisplayNameFor(model => model.PayRate): @Html.DisplayFor(model => model.PayRate)</h3>
<p>@Html.ActionLink("Edit Stylist", "Edit", new { id = Model.StylistId })</p>
<p>@Html.ActionLink("Delete Stylist", "Delete", new { id = Model.StylistId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

HairSalon/Views/Stylists/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h2>Edit</h2>

<h4>Edit this stylist info: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StylistId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name, new {@class = "form-control", type="text", required="text"})

  @Html.LabelFor(model => model.Speciallity)
  @Html.EditorFor(model => model.Speciallity, new {@class = "form-control", type="text", required="text"})

  @Html.LabelFor(model => model.PayRate)
  @Html.EditorFor(model => model.PayRate, new {@class = "form-control", type="number", step=".01", required="number"})

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list of stylists", "Index")</p>

HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;

<h1>Stylists</h1>

@if (@Model.Count == 0)
{
  <h3>There are no stylists yet!</h3>
}

<ul>
  @foreach (Stylist stylist in Model)
  {
    <li>@Html.ActionLink($"{stylist.Name}", "Details", new { id = stylist.StylistId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new stylist", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>